// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB32h6qq9_riVqZyMCEZLcZ1FS6yFmkQ_U',
    appId: '1:701644568940:web:a7f00427023a6f55179b49',
    messagingSenderId: '701644568940',
    projectId: 'act-connect',
    authDomain: 'act-connect.firebaseapp.com',
    storageBucket: 'act-connect.appspot.com',
    measurementId: 'G-RP8M4PWK96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqBSn2uJrG6X3l8AJJS9JcECZyIslgG0',
    appId: '1:701644568940:android:b2138de717464f22179b49',
    messagingSenderId: '701644568940',
    projectId: 'act-connect',
    storageBucket: 'act-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRkQRvPqsbfxvOGcIioBCDTxfkd1a_vtQ',
    appId: '1:701644568940:ios:1ac3dc797b568c32179b49',
    messagingSenderId: '701644568940',
    projectId: 'act-connect',
    storageBucket: 'act-connect.appspot.com',
    androidClientId: '701644568940-bd23jf4adrjjn3gek2vtb5lg7r9o4ndq.apps.googleusercontent.com',
    iosClientId: '701644568940-ek0sr8j9gheru0624sceetm3dmkbkrik.apps.googleusercontent.com',
    iosBundleId: 'com.example.kakeAutoparts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRkQRvPqsbfxvOGcIioBCDTxfkd1a_vtQ',
    appId: '1:701644568940:ios:1ac3dc797b568c32179b49',
    messagingSenderId: '701644568940',
    projectId: 'act-connect',
    storageBucket: 'act-connect.appspot.com',
    androidClientId: '701644568940-bd23jf4adrjjn3gek2vtb5lg7r9o4ndq.apps.googleusercontent.com',
    iosClientId: '701644568940-ek0sr8j9gheru0624sceetm3dmkbkrik.apps.googleusercontent.com',
    iosBundleId: 'com.example.kakeAutoparts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB32h6qq9_riVqZyMCEZLcZ1FS6yFmkQ_U',
    appId: '1:701644568940:web:f5b91860f05a21e2179b49',
    messagingSenderId: '701644568940',
    projectId: 'act-connect',
    authDomain: 'act-connect.firebaseapp.com',
    storageBucket: 'act-connect.appspot.com',
    measurementId: 'G-WDB46NMHHJ',
  );

}